Description = "Finds leaked secrets in a Git repository using Seekret"
Timeout = 600
Options = '{}'
AssetTypes = ["WebAddress"] # For testing. Should be "GitRepository".
RequiredVars = ["GITHUB_ENTERPRISE_TOKEN"]
