version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
  commit-message:
    prefix: "feat"
    include: "scope"
- package-ecosystem: "docker"
  directory: cmd/vulcan-nuclei
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
  commit-message:
    prefix: "feat"
    include: "scope"
- package-ecosystem: "docker"
  directory: cmd/vulcan-semgrep
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
  commit-message:
    prefix: "feat"
    include: "scope"
- package-ecosystem: "docker"
  directory: cmd/vulcan-trivy
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
  commit-message:
    prefix: "feat"
    include: "scope"
