rules:
  # Rule for including JWT tokens as secrets.
  # Source: https://github.com/aquasecurity/trivy/discussions/2496
  - id: jwt-token
    category: Generic
    title: JWT Token
    severity: HIGH
    description: 
    regex: '["'']?(?P<secret>eyJ[A-Za-z0-9_=-]{2,}\.[A-Za-z0-9_=-]{2,}\.[A-Za-z0-9_.+\/=-]{2,})["'']?'
    secret-group-name: secret
allow-rules:
  # Skip swagger files to reduce false positives.
  - id: skip-swagger
    description: skip swagger files
    path: swagger.*
  # Skip rst files to reduce false positives.
  - id: skip-rst
    description: skip rst files
    path: .*\.rst
disable-rules:
  # Disable cloud provider account user IDs as they are not secrets perse.
  - alibaba-access-key-id
  - aws-account-id
  - aws-access-key-id
  - gcp-service-account
  # This is meant to reside at client side, therefore shoul not be considered as a secret.
  - stripe-publishable-token
