Description = "Checks if an asset is vulnerable to a subdomain takeover according to the data in the Security Graph."
AssetTypes = ["Hostname", "WebAddress"]

Timeout = 3600 # 1 hour.

RequiredVars = [
  "GRAPH_INVENTORY_API_URL",
  "GRAPH_INVENTORY_API_INSECURE_SKIP_VERIFY"
]
