Description = "Runs an AWS Trusted Advisor check against an AWS account"
AssetTypes = ["AWSAccount"]
RequiredVars = ["VULCAN_ASSUME_ROLE_ENDPOINT", "ROLE_NAME", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY" ,"AWS_SESSION_TOKEN"]
Options = '{"refresh_timeout": 60}'
