Description = "Runs an AWS Trusted Advisor check against an AWS account"
AssetTypes = ["AWSAccount"]
Timeout = 900 # 15 minutes.
RequiredVars = ["VULCAN_ASSUME_ROLE_ENDPOINT", "ROLE_NAME"]
Options = '{"refresh_timeout": 600}'
