Description = "Finds potential secrets in source code from a Git repository using gitleaks"
Timeout = 900 # 15 minutes
AssetTypes = ["GitRepository"]
RequiredVars = []
Options = '{"depth": 1, "branch":""}'
