Description = "Finds potential secrets in source code from a Git repository using gitleaks"
Timeout = 900 # 15 minutes
AssetTypes = ["GitRepository"]
RequiredVars = ["GITHUB_ENTERPRISE_ENDPOINT", "GITHUB_ENTERPRISE_TOKEN"]
Options = '{"depth": 1, "branch":""}'
