Description = "Finds potential secrets in source code from a Git repository using gitleaks"
Timeout = 7200 # 2 hours
AssetTypes = ["GitRepository"]
RequiredVars = []
Options = '{"depth": 1, "branch":"", "ruleset":"p/r2c-security-audit"}'