Description = "Runs an OWASP ZAP passive or active scan"
AssetTypes = ["WebAddress"]
Timeout = 36000 # 10 hours. Expressed in seconds as an integer.
# Disabled scanners:
# 10062 - PII Disclosure - Too many false positive results.
# 10003 - Vulnerable JS Library - Duplicates the Retire.js check.
# 10108 - Reverse Tabnabbing - Not relevant for modern browser versions.
# Ignored scanners for fingerprint:
# 40018 - SQL Injection - Too many false positive results with variable resources.
# Source: https://www.zaproxy.org/docs/alerts/
Options = """{
    "depth": 2, 
    "active": true, 
    "min_score": 0, 
    "disabled_scanners": ["10062", "10003", "10108"],
    "ignored_fingerprint_scanners": ["40018"],
    "max_spider_duration": 0,
    "max_scan_duration": 0, 
    "max_rule_duration": 0,
    "openapi_url": "",
    "openapi_host": ""
    }"""
